spring.application.name=demo1

# Configuracion RabbitMQ
# spring.rabbitmq.host=localhost
# spring.rabbitmq.port=5672
# spring.rabbitmq.username=guest
# spring.rabbitmq.password=guest

# Datos de conexion a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tfg
#spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=root
spring.datasource.password=2De897e77777

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#Constantes
queue.file-processing=cola.ficheros

# Directorio donde llegan los ficheros XML
# file.input-dir=/app/resources/testfile
file.input-dir=C:/data/input

# Directorio donde se mueven los ficheros procesados correctamente
file.processed-dir=C:/data/processed

# Directorio donde se mueven los ficheros con error
file.error-dir=C:/data/error

api.terceros.url=http://host.docker.internal:9090

# Nivel de log
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

logging.file.name=C:/logs/demo1/application.log


